--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2025-05-31 下午 01:49:05
-- Server version: 10.4.8
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE oauth;

--
-- Drop table `_prisma_migrations`
--
DROP TABLE IF EXISTS _prisma_migrations;

--
-- Drop table `OAuthCode`
--
DROP TABLE IF EXISTS OAuthCode;

--
-- Drop table `OAuthToken`
--
DROP TABLE IF EXISTS OAuthToken;

--
-- Drop table `User`
--
DROP TABLE IF EXISTS User;

--
-- Set default database
--
USE oauth;

--
-- Create table `User`
--
CREATE TABLE User (
  id int(11) NOT NULL AUTO_INCREMENT,
  email varchar(191) NOT NULL,
  password varchar(191) NOT NULL,
  clientId varchar(191) NOT NULL,
  clientSecret varchar(191) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `User_clientId_key` on table `User`
--
ALTER TABLE User
ADD UNIQUE INDEX User_clientId_key (clientId);

--
-- Create index `User_clientSecret_key` on table `User`
--
ALTER TABLE User
ADD UNIQUE INDEX User_clientSecret_key (clientSecret);

--
-- Create index `User_email_key` on table `User`
--
ALTER TABLE User
ADD UNIQUE INDEX User_email_key (email);

--
-- Create table `OAuthToken`
--
CREATE TABLE OAuthToken (
  id int(11) NOT NULL AUTO_INCREMENT,
  accessToken varchar(191) NOT NULL,
  refreshToken varchar(191) NOT NULL,
  expiresAt datetime(3) NOT NULL,
  userId int(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 48,
AVG_ROW_LENGTH = 564,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `OAuthToken_accessToken_key` on table `OAuthToken`
--
ALTER TABLE OAuthToken
ADD UNIQUE INDEX OAuthToken_accessToken_key (accessToken);

--
-- Create index `OAuthToken_refreshToken_key` on table `OAuthToken`
--
ALTER TABLE OAuthToken
ADD UNIQUE INDEX OAuthToken_refreshToken_key (refreshToken);

--
-- Create foreign key
--
ALTER TABLE OAuthToken
ADD CONSTRAINT OAuthToken_userId_fkey FOREIGN KEY (userId)
REFERENCES User (id) ON UPDATE CASCADE;

--
-- Create table `OAuthCode`
--
CREATE TABLE OAuthCode (
  id int(11) NOT NULL AUTO_INCREMENT,
  code varchar(191) NOT NULL,
  expiresAt datetime(3) NOT NULL,
  userId int(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 44,
AVG_ROW_LENGTH = 399,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `OAuthCode_code_key` on table `OAuthCode`
--
ALTER TABLE OAuthCode
ADD UNIQUE INDEX OAuthCode_code_key (code);

--
-- Create foreign key
--
ALTER TABLE OAuthCode
ADD CONSTRAINT OAuthCode_userId_fkey FOREIGN KEY (userId)
REFERENCES User (id) ON UPDATE CASCADE;

--
-- Create table `_prisma_migrations`
--
CREATE TABLE _prisma_migrations (
  id varchar(36) NOT NULL,
  checksum varchar(64) NOT NULL,
  finished_at datetime(3) DEFAULT NULL,
  migration_name varchar(255) NOT NULL,
  logs text DEFAULT NULL,
  rolled_back_at datetime(3) DEFAULT NULL,
  started_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  applied_steps_count int(10) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

-- 
-- Dumping data for table User
--
INSERT INTO User VALUES
(1, 'user1@example.com', '$2b$10$ibQugUYqT.1RvqOZA3AqxuWbzo5QRsbQ1j9NnxTkQK/E5qpjPzpPu', 'clientId1', 'clientSecret1'),
(2, 'user2@example.com', '$2b$10$ibQugUYqT.1RvqOZA3AqxuWbzo5QRsbQ1j9NnxTkQK/E5qpjPzpPu', 'clientId2', 'clientSecret2'),
(3, 'user3@example.com', '$2b$10$ibQugUYqT.1RvqOZA3AqxuWbzo5QRsbQ1j9NnxTkQK/E5qpjPzpPu', 'clientId3', 'clientSecret3'),
(4, 'user4@example.com', '$2b$10$ibQugUYqT.1RvqOZA3AqxuWbzo5QRsbQ1j9NnxTkQK/E5qpjPzpPu', 'clientId4', 'clientSecret4'),
(5, 'user5@example.com', '$2b$10$ibQugUYqT.1RvqOZA3AqxuWbzo5QRsbQ1j9NnxTkQK/E5qpjPzpPu', 'clientId5', 'clientSecret5');

-- 
-- Dumping data for table _prisma_migrations
--
INSERT INTO _prisma_migrations VALUES
('43023bac-964c-4a53-bfe2-f55c83338ce8', 'aa9389202bf5f3e93b592a54d1b5b6ddb7dc7ed7f48c6082fc38aa822298e097', '2024-10-13 14:20:52.957', '20241013142052_init', NULL, NULL, '2024-10-13 14:20:52.856', 1);

-- 
-- Dumping data for table OAuthToken
--
INSERT INTO OAuthToken VALUES
(1, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkwMTE4MCwiZXhwIjoxNzI4OTQ0MzgwfQ.8Y0k_hF1MTkUuvSWLeWRN42Dyl4500UtsV7irciuxyo', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkwMTE4MCwiZXhwIjoxNzI5NTA1OTgwfQ.UvPAvGSUW67r-8EgIzqQniwLUR4hx3ENNxNysnwLYnM', '2024-10-14 22:19:40.702', 1),
(2, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkxMzk3OCwiZXhwIjoxNzI4OTU3MTc4fQ.pHxkJjvDDZ12_kEtjOaNhiwmB0N70JmBQybNY8PsooM', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkxMzk3OCwiZXhwIjoxNzI5NTE4Nzc4fQ.IvSlWVJoG6M7KTjN0yKwA_pbDHxPwYYT4kYs7_hH3So', '2024-10-15 01:52:58.284', 1),
(3, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDM3OCwiZXhwIjoxNzI4OTYzNTc4fQ.uO-lvi0LDLCMfnLz59osn7JKOT8sRxzr2HI3DJKFTrA', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDM3OCwiZXhwIjoxNzI5NTI1MTc4fQ.H7GWPcqDX5IUU5LNoxGt6JLnxQcqEmnv2ZsFvgFfIjI', '2024-10-15 03:39:38.806', 1),
(5, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDQ5NywiZXhwIjoxNzI4OTYzNjk3fQ.p-NdQtHSp5PDp3-VCgRE9ll-O1-T7bTnXYVNQze8rQI', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDQ5NywiZXhwIjoxNzI5NTI1Mjk3fQ.JdOg6g0N-1YIs12VbXYSATGKmqo3CbLJKgdImlPZtfg', '2024-10-15 03:41:38.049', 1),
(6, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDU0NSwiZXhwIjoxNzI4OTYzNzQ1fQ._sMTrH-5uLztxNQMQgjwdimsYW42H_abUQ2vKVWfFHE', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDU0NSwiZXhwIjoxNzI5NTI1MzQ1fQ.tIwbCY1wL9vMVV8WJ_jQSIIBDxz4zNxzhb-0fZzQu_o', '2024-10-15 03:42:25.677', 1),
(7, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDU2OSwiZXhwIjoxNzI4OTYzNzY5fQ.28feulN8mPIsa5z5CLXJn1vmHFGwH9rAdY3-0AydgHc', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDU2OSwiZXhwIjoxNzI5NTI1MzY5fQ.3Mp_SUZQgDIjWO7RLSX6B_iRMEJcadOSJk7bBFIlsPg', '2024-10-15 03:42:49.692', 1),
(9, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDY1OSwiZXhwIjoxNzI4OTYzODU5fQ.76RYk8XHTL_yvijxBq15v-xViLIzqeiaa_26NpnKEkY', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDY1OSwiZXhwIjoxNzI5NTI1NDU5fQ.IvFLcKpYXKsybxc-FahxBycrZ6D2F8SWlgmk8rJsHcg', '2024-10-15 03:44:19.253', 1),
(10, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDY2MCwiZXhwIjoxNzI4OTYzODYwfQ.BM7YjLB9kwqCBjQXQkzM47HA3O7fXu4rTy0Vrp49x9A', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDY2MCwiZXhwIjoxNzI5NTI1NDYwfQ.OSCgu-linAu9yrbxE0XFl8Dctx_Qs8M8CKAxYKCFS3I', '2024-10-15 03:44:20.839', 1),
(12, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDcyMSwiZXhwIjoxNzI4OTYzOTIxfQ.cK33TmEsswpz_p5wpOJXKNIrRnDbz82T0AI2mdJAebU', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDcyMSwiZXhwIjoxNzI5NTI1NTIxfQ.gz_IRKXoJy84INytgw-CC60UHCO_scnTF28v6kPP-Bg', '2024-10-15 03:45:21.64', 1),
(14, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDc4OSwiZXhwIjoxNzI4OTYzOTg5fQ.GQzKY-_Me8pKv6EnVoy_hAAYY-jv1XpBK30r4MhWeTM', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDc4OSwiZXhwIjoxNzI5NTI1NTg5fQ.CYC8Zhmbdt1M3H9yVFujY5afin_MIkjrkdIBrblPmm8', '2024-10-15 03:46:29.483', 1),
(15, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDc5NiwiZXhwIjoxNzI4OTYzOTk2fQ.R-DL9SUHv-TYxfbeTHZ64DmjWheWMPcIZ3cVj7uask4', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDc5NiwiZXhwIjoxNzI5NTI1NTk2fQ.j98SpV4mT-_IjfjAQIcj4JVVN7ohoysiNOabX8r-R5Y', '2024-10-15 03:46:36.908', 1),
(16, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDc5OSwiZXhwIjoxNzI4OTYzOTk5fQ.Fzopnl611dyAT5jWnTCWQUzBTmSibSmOjB76hqqX2Ds', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDc5OSwiZXhwIjoxNzI5NTI1NTk5fQ.VPJL_ukAVtdRxbJ5851pDr2pV-EVeMsjGHPD6tzgtgo', '2024-10-15 03:46:39.639', 1),
(17, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDgxMCwiZXhwIjoxNzI4OTY0MDEwfQ.e8ko-BD_Wq-DTbFKKzM3Mpu0iQaaMiC0yL1x9kqKbqI', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDgxMCwiZXhwIjoxNzI5NTI1NjEwfQ.1QAP7urYLkRpREOug6Zov-bHZaO13KQREqDcVh6si_g', '2024-10-15 03:46:50.677', 1),
(18, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDgxNCwiZXhwIjoxNzI4OTY0MDE0fQ.isLUe8VfKgbfL-PVmR1WaAn3W7eegTLsBq08_FP5dlg', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDgxNCwiZXhwIjoxNzI5NTI1NjE0fQ.M4-Sxv6lp4Y4Xx4NJNc89etf_pCYdWqPA2PuPWWEwKY', '2024-10-15 03:46:54.491', 1),
(19, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDgyNiwiZXhwIjoxNzI4OTY0MDI2fQ.Z_qyBTlgMOQfpYa1tpUaenDyG7ty3PoG71SySscYTik', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDgyNiwiZXhwIjoxNzI5NTI1NjI2fQ.5pAszrKx4X4JbY6jSh_-bqqYOUkWQFgyN798VL1u9v4', '2024-10-15 03:47:06.433', 1),
(20, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDg1MywiZXhwIjoxNzI4OTY0MDUzfQ.afxQ9pgQW0n4u3ZIjJvgiLjnZDbwrKgiUXXX4Cnq2FY', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDg1MywiZXhwIjoxNzI5NTI1NjUzfQ.00GXqHF803n0V35srvW8aQkbPnw85sA2QDvzdF8Xpmw', '2024-10-15 03:47:33.945', 1),
(22, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDg1NywiZXhwIjoxNzI4OTY0MDU3fQ.GnzoeLV2C0EaWW2qnEJc46ZrN4ixcOPsusKIrd6qkM4', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDg1NywiZXhwIjoxNzI5NTI1NjU3fQ.1bkfAxAPuOO-000U11Lk1gGu8wj3AJ4HswzCdnqb-Sw', '2024-10-15 03:47:37.03', 1),
(24, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDg2NSwiZXhwIjoxNzI4OTY0MDY1fQ.8asY19e_r35I5FTbT8tShXcpLs8t2rc8M1odpXCtDt0', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDg2NSwiZXhwIjoxNzI5NTI1NjY1fQ.S8QSynV6ukVtkJKauMVcxlsZf9_y8cnHi_URp4lSjy8', '2024-10-15 03:47:45.808', 1),
(26, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDg3OSwiZXhwIjoxNzI4OTY0MDc5fQ.9gZxdTIpM3RUO8sjWgUyRwZ6dxH5pmJ_kpU93BQsnHQ', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDg3OSwiZXhwIjoxNzI5NTI1Njc5fQ.bbo5_Ry_WVvJdcND3y3s1nqGR59g835Re6qira3IZmY', '2024-10-15 03:47:59.61', 1),
(28, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDg4NSwiZXhwIjoxNzI4OTY0MDg1fQ.7-kF62HXYPlVdQ9_o1bHqEtQ_bBMNGW0_cphqapFJc4', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDg4NSwiZXhwIjoxNzI5NTI1Njg1fQ.uJnP2RNibdWg0Y0CEXYdH7a7n3W5EiFlzjlShIAG4I4', '2024-10-15 03:48:05.127', 1),
(30, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDg4OSwiZXhwIjoxNzI4OTY0MDg5fQ.qk-YlupZJwfI6twGbWSlvTq_dHPa2bihzQhQaHlojis', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDg4OSwiZXhwIjoxNzI5NTI1Njg5fQ.UnPpqogg046yKsMRYO7YTMijqye6RAUskdVUnURlkFk', '2024-10-15 03:48:09.53', 1),
(31, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDg5NSwiZXhwIjoxNzI4OTY0MDk1fQ.y1rP_Z9_VXzMrPZ5W47OpKGTO0Vz1iN2AcFfq4c6hTQ', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDg5NSwiZXhwIjoxNzI5NTI1Njk1fQ.j-CYut6YlmvAExolCPSNbKDHg5Ysv5Ph5kvhdEOM1ys', '2024-10-15 03:48:15.053', 1),
(33, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDg5OCwiZXhwIjoxNzI4OTY0MDk4fQ.Q2C2EMyAydQC6uaX7_Jf3NiPe0JOYVg55EsBbkvhsxE', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDg5OCwiZXhwIjoxNzI5NTI1Njk4fQ.BjTw4l9Sf-xNas0uoAP1CbjQfLuNWpEInCKUunYj5LU', '2024-10-15 03:48:18.207', 1),
(35, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDkwOCwiZXhwIjoxNzI4OTY0MTA4fQ.01nCyf0nBDQeyL12dZ66-0pIp743vtdHLYxPbbjHHKY', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDkwOCwiZXhwIjoxNzI5NTI1NzA4fQ.tQFf_AxB7JWrvJ_wFaIK8R6wIDvVyX2X86Nan-wVHzw', '2024-10-15 03:48:28.399', 1),
(36, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDkxMywiZXhwIjoxNzI4OTY0MTEzfQ.vURGZpzOb8lOT9Wl5llSgtxMBHzqLtNuBMyj3klMgjM', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMDkxMywiZXhwIjoxNzI5NTI1NzEzfQ.92Z8R17sLFO8aftoo4D26yG85AuNyQ2V9AkNhAUJ7mk', '2024-10-15 03:48:33.89', 1),
(38, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMTEwMSwiZXhwIjoxNzI4OTY0MzAxfQ.VSYW0zQS_Qm5GmtKlnqqlf2Q9AyoeLU_8LjpWHiOaYQ', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMTEwMSwiZXhwIjoxNzI5NTI1OTAxfQ.xFSopjHuCcimx2HfvHsSmY8raQrGMjWG-7vvxcelARI', '2024-10-15 03:51:41.362', 1),
(40, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMTU0MiwiZXhwIjoxNzI4OTY0NzQyfQ.f7laleG6oAF4vSiBQkh8lluYsQkV_6NjaMDOD-0kG6Q', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMTU0MiwiZXhwIjoxNzI5NTI2MzQyfQ.7lCRP1KQEbWU-qISd9t5BENLzg7y2W4JUONLMG9BeX8', '2024-10-15 03:59:02.051', 1),
(42, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMTU1NiwiZXhwIjoxNzI4OTY0NzU2fQ.SXXwmvSwEe40my-4pv1vWCZqozoKglf6KvA-6UXaRAA', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMTU1NiwiZXhwIjoxNzI5NTI2MzU2fQ.D4efsfw47Qi97RwyraGLECYQepZKpqIBPr0POsjwCt4', '2024-10-15 03:59:16.352', 1),
(44, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMTU5MCwiZXhwIjoxNzI4OTY0NzkwfQ.PYA9LHkasbx4fOWXxTNn-dEVsllg_JHy8No9xUKYAhk', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMTU5MCwiZXhwIjoxNzI5NTI2MzkwfQ.WRMDoV-gbr9SZR-cwckn9XAmiPJH3y2mJ5jLC126SE4', '2024-10-15 03:59:50.231', 1),
(45, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMTU5NCwiZXhwIjoxNzI4OTY0Nzk0fQ.C3gzxCb51dmXa_BPkn1xVCLok5TcLi05UaRYczlBQUk', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMTU5NCwiZXhwIjoxNzI5NTI2Mzk0fQ.edACHCnRc-Zu6ezrGuig-4yhc6XTxmObMGIRl7wCnCQ', '2024-10-15 03:59:54.998', 1),
(46, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMTYwMCwiZXhwIjoxNzI4OTY0ODAwfQ.DBAqRGi-V7VW4xtfWxAs9XYxe0w5hXDRqBVbGfgxiS0', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyODkyMTYwMCwiZXhwIjoxNzI5NTI2NDAwfQ.pulrBytgUv-PVSnc11AATvXOaAolgE-FYkcQ1Q41tBU', '2024-10-15 04:00:00.234', 1);

-- 
-- Dumping data for table OAuthCode
--
INSERT INTO OAuthCode VALUES
(1, '092a23b7-783a-44fc-8cae-95b81482b275', '2024-10-13 14:32:16.092', 1),
(2, '676e9d62-68a2-45bc-b615-c90b9a58a114', '2024-10-13 14:32:21.678', 1),
(3, 'f74acceb-c607-4c5b-a2c4-b1ebbc73d757', '2024-10-13 14:32:33.98', 1),
(4, '900090f6-ef50-4215-bc02-a0e8b04f0957', '2024-10-13 14:33:02.623', 1),
(5, '36377775-7b2d-4a7d-a0cd-67276ac635b9', '2024-10-13 14:33:35.463', 1),
(6, '06a5a955-a35f-4126-9acd-35a3ba036a94', '2024-10-13 14:33:28.865', 1),
(7, '5d11964c-247c-4979-85d1-2a8ac6014434', '2024-10-13 14:37:22.835', 1),
(8, '6861b82c-f735-4154-9963-094350709d9e', '2024-10-13 14:37:42.975', 1),
(9, '15a0b99c-bdcd-4e82-8b5c-6d684c9acd14', '2024-10-13 14:37:50.761', 1),
(10, '9f1a14be-2196-4a52-9e02-1aeb6c0eba01', '2024-10-13 14:37:51.125', 1),
(11, '5eed8a47-3868-44bc-a094-060098c5909c', '2024-10-13 14:37:52.202', 1),
(12, 'ba34c01a-2122-4e6e-8a7f-fba95f114cb2', '2024-10-13 14:38:02.111', 1),
(13, '03eedaad-88ed-4eba-b7cc-04058af9455a', '2024-10-13 14:38:14.874', 1),
(14, 'f5bd7f2d-ca47-4e97-8dcd-c126f802da85', '2024-10-13 14:38:21.38', 1),
(15, '4a0df5a6-b158-494f-a9d4-907893be42b6', '2024-10-13 14:38:26.214', 1),
(16, '44217af6-c2b6-4b0d-836f-578a7ccf5d28', '2024-10-13 14:38:57.851', 1),
(17, 'e1ccdf4f-65f0-448a-a8b1-62596fb3e3b0', '2024-10-13 14:39:12.613', 1),
(18, '1b37ea54-d5a5-4d1f-a222-0292bdebdeaf', '2024-10-13 14:39:32.634', 1),
(19, '9a8bcb7f-a1c9-436c-bf65-482846a6ec52', '2024-10-13 14:41:54.938', 1),
(20, 'fe408c61-e36c-4744-b799-1b86fedabcd3', '2024-10-13 14:42:23.85', 1),
(21, '158549cc-6844-4042-a4e9-9220be2f6d4c', '2024-10-13 14:43:12.123', 1),
(22, '24f85bb2-152a-40e6-8817-3236ad1b8339', '2024-10-13 14:45:14.35', 1),
(23, '1ecb1b8e-e349-43af-98c0-18a4b9a49a05', '2024-10-13 14:45:53.308', 1),
(24, '3536f192-fb17-4ce3-9684-5bda10b944c0', '2024-10-13 14:46:06.527', 1),
(25, 'f8bb4a15-ce31-4ebf-8a9f-254648473435', '2024-10-13 14:46:37.661', 1),
(26, '2b8af17a-385d-400d-9701-74c9476624be', '2024-10-13 14:48:37.168', 1),
(27, '93e8dc0e-f3a5-418e-98ae-a5e67374a3f4', '2024-10-13 14:48:59.431', 1),
(28, '92873722-4bb8-400e-8ab7-14e53c62d3d0', '2024-10-13 14:49:40.315', 1),
(29, '9e9dc9ca-7389-495c-aecd-f080e7e56eae', '2024-10-13 14:53:20.262', 1),
(30, 'fa37e234-01b2-4598-a56b-e542123d7ceb', '2024-10-14 10:29:33.452', 1),
(31, 'c0348445-b037-40be-a2a9-76a8605d163e', '2024-10-14 14:02:53.899', 1),
(32, '736a556a-de49-497a-8856-b678e13c04d1', '2024-10-14 14:56:40.173', 1),
(33, 'f3bac28d-b449-4357-9ee3-ee1321fb5209', '2024-10-14 14:56:48.67', 1),
(34, 'e45072f2-d381-439b-8010-b7069cf97db5', '2024-10-14 14:57:27.654', 1),
(35, 'bd6d4b06-a74a-407e-9308-36d35a063089', '2024-10-14 14:58:10.901', 1),
(36, 'ad509bf0-808f-442b-ba8c-00ed92fcf704', '2024-10-14 15:00:50.447', 1),
(37, '23518cb8-e52b-4c43-b0a9-815cd8d11e99', '2024-10-14 15:01:25.167', 1),
(38, 'ee4088ce-7470-4f60-84f2-e8c7de3fe25f', '2024-10-14 15:02:50.58', 1),
(39, '636f26fe-a545-44eb-b6fd-ca93bb3e0e18', '2024-10-14 15:05:57.188', 1),
(40, '5d393f00-2702-4f29-b67b-4ecc2a897893', '2024-10-14 15:08:44.34', 1),
(41, '1c63d989-4ec8-475c-b194-c13f8930469e', '2024-10-14 15:49:07.436', 1),
(42, '683c5856-61e3-40a6-9f99-5dc4243dad20', '2024-10-14 16:01:39.986', 1),
(43, '793d8951-6863-460a-ab2f-25354c9592b5', '2024-10-14 16:09:00.021', 1);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;