GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'oauth'@'%' IDENTIFIED BY 'uNstHgqg';
GRANT ALL PRIVILEGES ON oauth.* TO 'oauth'@'%';
GRANT ALL PRIVILEGES ON *.* TO 'oauth'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

ALTER DATABASE `oauth` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;


