
# @name test
curl -X GET "http://localhost:3000/oauth/test?userId=123"



# @name loginError
curl -X POST "http://localhost:3000/oauth/login" \
-H "Content-Type: application/json" \
-d '{
    "email": "",
    "password": "password123",
    "redirectUri": "http://localhost:3001/oauth/authorize"
}'


# @name login
curl -X POST "http://localhost:3000/oauth/login" \
-H "Content-Type: application/json" \
-d '{
    "email": "user1@example.com",
    "password": "password123",
    "redirectUri": "http://localhost:3001/oauth/authorize"
}'


# @name verify
@code={{login.response.body.data.code}}
curl -X POST http://localhost:3000/oauth/validate \
-H "Content-Type: application/json" \
-d '{
  "code": "{{code}}"
}'


# @name token
curl -X POST http://localhost:3000/oauth/token \
  -H "Content-Type: application/json" \
  -d '{"code": "your-authorization-code", "clientId": "your-client-id", "clientSecret": "your-client-secret"}'

# @name refresh
curl -X POST http://localhost:3000/oauth/refresh \
  -H "Content-Type: application/json" \
  -d '{"refreshToken": "your-refresh-token"}'
